# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    auth
    # increment_build_number(xcodeproj: "dg-muscle-ios.xcodeproj")
    build_app(scheme: "dg-muscle-ios", destination: "generic/platform=iOS")
    upload_to_testflight
  end

  desc "Authenticate"
  lane :auth do
    api_key = app_store_connect_api_key(
      key_id: "LPRRPF9RMN",
      # issuer_id 가 뭐지?
      # issuer_id: "6053b7fe-68a8-4acb-89be-165aa6465141",
      key_filepath: "./AuthKey_LPRRPF9RMN.p8"
    )

    pilot(api_key: api_key)
  end
end
